project_id = "qcjxihsgtsufivofhfjc"

[functions.analyze-performance]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.send-metric-reminders]
verify_jwt = false

[functions.send-team-member-welcome]
verify_jwt = true

[functions.send-report-reminders]
verify_jwt = false